#
# Copyright (C) 2008-2016 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Transmission
PKG_VERSION:=1.0.0
LUCI_DEPENDS:=+luci-lib-ipkg

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
